# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

image:
  file: Dockerfile.gitpod

tasks:
  - init: yarn install
    command: yarn nx run home:serve:development

ports:
  - port: 4200
    visibility: public
    onOpen: open-preview
